---
title: "Data Challenge 3"
output: html_document
---

[github link] (https://github.com/kelseyaguirre/Data_Challenge_3.git)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, results = 'asis')
```
### Load Libraries
```{r}
##load in libraries
library(readr)
library(tidyverse)
library(lubridate)
library(stringr)
library(ggplot2)
library(purrr)
library(knitr)
library(kableExtra)
```

## Question 1

```{r}
##read in the coffee data using map_dfr
##does reading and binding of the rows in one
##not binding here because it's all in one file?
coffee_ratings <- map_dfr('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv', read_csv)

##function to return mean and sd for different columns 
stats <- function(x) {
  ##keep mean[sd] in the same cell and round to 2 decimal places
  calc <- paste0(round(mean(x), 2),"[",round(sd(x), 2),"]")
  return(calc)
}

##function to use 'stats' and returns mean and sd for aroma:moisture columns
coffee_wrangler <- function(df, x){
  ##df because the dataframe can be later passed in
  coffee_subset <- df %>%
    ##dplyr doesn't play well w strings, renaming helps
    rename(group = x) %>%
    ##change troup to character
    mutate(group = as.character(group)) %>% 
    ##group by the variable i define as x
    group_by(group) %>% 
    ##summarise select columns with the stats function
    summarise(across(aroma:moisture, stats)) %>%
    ##re-categorize NAs from the df to 'Missing' and group them
    mutate(group = if_else(is.na(group), 'Missing',
                           group))
  ##capitalize the first letter for the column and remove the underscore
  #mutate(group = str_to_title(gsub("_", " ", group)))
  ##not working and I have no idea why, please help me understand for next time

  ##create the tables usning the kable function
  knitr::kable(coffee_subset, format = 'html', 
               ##create caption to specify the table contents
               caption = paste0("Mean and SD for Aroma through Moisture for ", x)) %>% 
    ##using the kableExtra package to make the tables more attractive
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
}

##bin the data for altitude mean meters to make it easier to look at
coffee_ratings <- coffee_ratings %>% 
  mutate(bin_alt_mean_meters = cut(altitude_mean_meters, breaks=c(0, 1000, 2000),
             labels = c("0-1000", "1000-2000")))
```

### Values in tables are Mean[SD]
```{r}
##produce three separate tables
map(c('species',
      'country_of_origin',
      'bin_alt_mean_meters'),
    coffee_wrangler,
    df = coffee_ratings)
```


## Question 2

```{r}
##filter out the zeros for plot 1
viz_coffee <- filter_at(coffee_ratings, vars(aroma:balance), any_vars(. > 0))

##create a function that plots two variables and colors by group
viz_tool <- function(df, x, y, c){
  df %>% ggplot(aes(x = {{x}}, y = {{y}}, col = {{c}})) +
    geom_point()
}
```

### Plot 1: Aroma vs Flavor Separated by Species
```{r}
##execute plot 1
viz_tool(viz_coffee, aroma, flavor, species)
```

### Plot 2: Balance vs Body Separated by Binned Altitude Meters
```{r}
##execute plot 2
viz_tool(viz_coffee, balance, body, bin_alt_mean_meters)
```
