---
title: "Lab 3"
output: html_document
---

[github link] (https://github.com/kelseyaguirre/Lab_3.git)

## Data Science I
## Question 1

```{r}
##question 1
##setting the seed so it's reproducible
set.seed(42)

##selects a door and the door with the prize behind it
##choice within the function will be for switch = TRUE or FALSE
lab3_fun1 <- function(choice){
  ##setting the ints as characters and establishing 1-3
  doors <- as.character(1:3)
  ##for 1.a
  ##sample both the contestent pick and the prize at once
  picks <- sample(doors, size = 2, replace = TRUE)
  ##separate out just the contestent pick
  cont_pick <- unlist(picks)[1]
  ##separate out just the prize pick
  prize <- unlist(picks)[2]
  ##if the contestent picks the prize door, resample to get one of the two doors without the prize
  correct <- sample(doors[!doors%in%c(cont_pick)], size = 1)
  ##if the contestent picks the wrong door, open the other door without the prize
  incorrect <- doors[!doors%in%c(cont_pick, prize)]
  ##for 1.b
  ##set up the function to return a door that hasn't been picked yet and doesn't have the prize
  offer <- ifelse(cont_pick == prize, 
                  ##this is for 1.b.1
                  correct,
                  ##this is for 1.b.2
                  incorrect)
  ##for 1.c 
  ##if choice is switch (switch = TRUE), switch the contestents original pick to the door that wasn't originally picked, or just revealed
  ##if choice is stick (switch = FALSE), keep contestent's original pick
  if (choice == 'switch') {
    cont_pick <- doors[!doors%in%c(cont_pick, offer)]
    }
  ##for 1.d
  ##shows if the contestent won (TRUE) or lost (FALSE)
  ifelse(cont_pick == prize, TRUE, FALSE)
}

```

## Question 2

```{r}
##running the actual simulation
simulation <- function(n){
  ##find the mean if we use switch n times
  switching <- replicate(n, lab3_fun1('switch'))
  print(mean(switching))
  ##find the mean if we use stick n times
  stick <- replicate(n, lab3_fun1('stick'))
  print(mean(stick))
}
##to repeat both options 1000x
simulation(1000)
```

